"use client";

import { useState, type CSSProperties } from "react";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, CircleCheck, Headphones, LockKeyhole, MapPin, Menu, PhoneCall, ShieldCheck, ShoppingBag, Store, UserRoundCheck } from "lucide-react";
import styles from "./cannabis-design-lab.module.css";

export type ConceptId = "after-hours" | "sale-in-call" | "calm-control";
export const conceptNames: Record<ConceptId, string> = { "after-hours": "After Hours", "sale-in-call": "The Sale in the Call", "calm-control": "Calm Control" };

const scenarios = [
  { tab: "Menu", q: "Do you still have Blue Dream?", a: "The Downtown menu shows three options in stock. Want the current sizes and prices?", outcome: "Menu checked · visit intent captured" },
  { tab: "Deals", q: "What’s on special today?", a: "Downtown has an approved flower offer today. I can explain it and text the details.", outcome: "Promotion verified · details sent" },
  { tab: "Pickup", q: "Is my pickup ready?", a: "I found your order. It’s ready at the Downtown counter until 9 PM.", outcome: "Order found · status confirmed" },
  { tab: "First visit", q: "I’ve never been in. What do I need?", a: "Bring a valid government-issued ID. I can also text parking and entry directions.", outcome: "Policy answered · directions offered" },
];

export function CannabisDesignLab({ initialConcept = "after-hours" }: { initialConcept?: ConceptId }) {
  const [scenario, setScenario] = useState(0);
  const concept = initialConcept;
  return <main id="main-content" data-cannabis-design className={`${styles.page} ${styles[camel(concept)]}`}>
    <LocalNav concept={concept} />
    <Hero concept={concept} />
    <Pricing concept={concept} />
    <TrustRail concept={concept} />
    <Pain concept={concept} />
    <Outcomes concept={concept} />
    <Scenarios active={scenario} setActive={setScenario} concept={concept} />
    {concept === "sale-in-call" ? <CallReceipt /> : null}
    {concept === "calm-control" ? <ConversationLibrary /> : null}
    <Integrations concept={concept} />
    <Personalization concept={concept} />
    <Compliance concept={concept} />
    {concept === "calm-control" ? <Locations /> : null}
    <Setup concept={concept} />
    <FAQ />
    <RiskReversal />
    <Close concept={concept} />
    <LocalFooter />
  </main>;
}

function LocalNav({ concept }: { concept: ConceptId }) {
  return <nav className={styles.nav}><Link href="/" className={styles.logo}><i />BAMBOO AI</Link><div className={styles.navLinks}><a href="#calls">How Sage works</a><a href="#integrations">Integrations</a><a href="#control">Compliance</a><a href="#faq">FAQ</a></div><a href="/free-agent-builder?industry=Cannabis" className={styles.navButton}>Build Sage <ArrowRight /></a><button className={styles.menuButton} aria-label="Open menu"><Menu /></button><span className={styles.conceptName}>{conceptNames[concept]}</span></nav>;
}

function Hero({ concept }: { concept: ConceptId }) {
  if (concept === "sale-in-call") return <section className={styles.heroSale}><div className={styles.saleCopy}><span>Sage · AI phone agent for dispensaries</span><h1>Turn “Do you have this?” into “I’m on my way.”</h1><p>Sage answers every call, checks the right store information, and gives every caller a useful next step.</p><Actions /></div><CallPath /></section>;
  if (concept === "calm-control") return <section className={styles.heroCalm}><div className={styles.calmCopy}><span>Sage</span><h1>The phone agent your store can actually control.</h1><p>Sage answers menu questions, explains promotions and loyalty, handles pickup and directions, and takes care of routine calls—so your staff can stay with the customers in front of them.</p><Actions /></div><div className={styles.heroPhoto}><CallTranscript /></div></section>;
  return <section className={styles.heroAfter}><div className={styles.afterShade} /><div className={styles.afterCopy}><span>Sage · AI phone agent for dispensaries</span><h1>The line is out<br />the door. The phone<br />still gets <em>answered.</em></h1><p>Sage answers every call with the right store hours, directions, menu availability, pickup details, loyalty information, and approved specials—so you never miss a customer.</p><Actions /></div><CallTranscript /></section>;
}

function Actions() { return <div className={styles.actions}><a href="/free-agent-builder?industry=Cannabis">Build and test Sage <ArrowRight /></a><button><PhoneCall /> Hear Sage answer</button></div>; }

function Pricing({ concept }: { concept: ConceptId }) {
  const plans = [
    ["Good","$119","One store, phones handled",["One location","Hours, directions, policies, specials","Age-gated approved scripts","Call log, summaries, human handoff"]],
    ["Better","$199","For stores that run on their systems",["Everything in Good","Live menu via supported POS connections","Loyalty balances and pickup workflows","SMS follow-up and directions by text"]],
    ["Best","$279","For multi-location retailers",["Everything in Better","Multi-location routing and store rules","Centralized conversation review","VIP and manager escalation routing"]],
  ] as const;
  return <section className={`${styles.pricing} ${styles[`${camel(concept)}Pricing`]}`}><div className={styles.pricingLead}><span>Pricing</span><h2>Build and test first.<br/>Pay when it goes live.</h2><p>Set up Sage, call it yourself, and challenge it with your most common questions. Nothing goes on your phone line until you publish.</p></div><div className={styles.planGrid}>{plans.map(([name,price,note,features],i)=><article className={i===1?styles.featuredPlan:""} key={name}><span>{name}</span><h3>{price}<small>/mo</small></h3><p>{note}</p><ul>{features.map(f=><li key={f}><Check/> {f}</li>)}</ul><a href="/free-agent-builder?industry=Cannabis">Start with {name}</a></article>)}</div><small className={styles.pricingNote}>Build and test before going live · per location · no pressure to publish</small></section>;
}

function TrustRail({ concept }: { concept: ConceptId }) { const items = concept === "after-hours" ? ["Always on during the rush", "Trained on your store", "Every call leaves an outcome", "Test before launch"] : ["Approved store knowledge", "Human handoff built in", "Permission-based personalization", "Location-specific control"]; return <section className={styles.trustRail}>{items.map((item,i)=><div key={item}><span>{String(i+1).padStart(2,"0")}</span><b>{item}</b></div>)}</section>; }

function CallTranscript() { return <div className={styles.transcript} aria-label="Animated example call"><header><span><i /> Live call in progress</span><time>00:37</time></header><div className={styles.voiceWave} aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} />)}</div><p className={styles.callLine}><b>Caller</b> Do you have Blue Dream in stock?</p><p className={styles.callLine}><b>Sage</b> Downtown has three options available. Want the current sizes and today’s approved offer?</p><p className={styles.callLine}><b>Caller</b> Yes. I’ll stop by after work.</p><div className={styles.callActions}><span><MapPin /> Downtown selected</span><span><ShoppingBag /> Menu checked</span><span><PhoneCall /> Directions queued</span></div><footer><CircleCheck /> Visit intent captured · next step ready</footer></div>; }

function CallPath() { return <div className={styles.callPath} aria-label="Animated call workflow">{["Caller question", "Location confirmed", "Menu checked", "Deal verified", "Directions sent", "Visit intent captured"].map((x,i)=><div key={x} style={{"--step":i} as CSSProperties}><b>{String(i+1).padStart(2,"0")}</b><span>{x}<small>{["Do you have Blue Dream?","Downtown · open until 10","Three options available","Approved offer found","Text message prepared","Customer visiting today"][i]}</small></span>{i===5?<Check />:<i />}</div>)}</div>; }

function Pain({ concept }: { concept: ConceptId }) {
  if (concept === "after-hours") return <section className={`${styles.pain} ${styles.afterPressure}`}><div className={styles.painCopy}><span>Friday · peak traffic</span><h2>Your phone is blowing up.</h2><p>Questions. Pickup updates. Directions. Deals. While your team helps the people in front of them, Sage keeps every caller moving toward the store.</p><ul className={styles.pressureList}><li><Check /> No routine call waits for the counter</li><li><Check /> Every answer uses the right location</li><li><Check /> Every conversation ends with a next step</li></ul></div><div className={styles.painPhoto}><div className={styles.pressureMetrics}><article><b>Peak hours</b><span>Calls keep ringing while the floor stays busy.</span></article><article><b>One question</b><span>Can decide which store earns the visit.</span></article><article><b>Every call</b><span>Leaves intent, context, and a clear outcome.</span></article></div></div></section>;
  if (concept === "sale-in-call") return <section className={`${styles.pain} ${styles.saleProblem}`}><div className={styles.phoneProblem}><div className={styles.phoneVisual} aria-label="Ringing telephone"/><div><span>The response problem</span><h2>Every missed call is revenue walking out.</h2><p>They asked about a product. Nobody answered. They called someone else.</p></div></div><div className={styles.problemPoints}><p>Calls go unanswered during busy times.</p><p>Questions go unresolved.</p><p>Shoppers leave without visiting.</p><p>Your team gets interrupted.</p></div><div className={styles.vsBand}><article><b>Without Sage</b><span>Rings go unanswered</span><span>Shoppers lose trust</span><span>Sales walk to competitors</span><span>Opportunities disappear</span></article><strong>VS</strong><article><b>With Sage</b><span><Check /> Every call answered</span><span><Check /> Accurate store answers</span><span><Check /> Promotions drive visits</span><span><Check /> Every call gets a next step</span></article></div></section>;
  return <section className={`${styles.pain} ${styles.calmDifference}`}><div className={styles.sectionLead}><span>The difference customers feel</span><h2>Protect the counter without abandoning the caller.</h2></div><div className={styles.counterCompare}><article><div className={styles.counterImage} data-state="interrupted"/><div><b>Interrupted counter</b><p>Calls pull staff away from the floor.</p><p>Customers wait longer.</p><p>Simple questions go unanswered.</p><p>Promotions and hot sales get missed.</p></div></article><article><div className={styles.counterImage} data-state="protected"/><div><b>Protected counter</b><p><Check /> Routine calls handled end to end.</p><p><Check /> Staff stays present with customers.</p><p><Check /> Accurate answers every time.</p><p><Check /> More time for better conversations.</p></div></article></div></section>;
}

function Outcomes({ concept }: { concept: ConceptId }) {
  if (concept !== "after-hours") return null;
  const steps = [["Listen","Understand intent, context, and what the caller really needs."],["Check","Read the right store’s menu, hours, policies, loyalty, and approved offers."],["Answer","Respond clearly in the store’s voice without guessing or making prohibited claims."],["Capture","Record visit intent, text the next step, or hand the call to a person with context."]];
  return <section className={styles.outcomes}><div className={styles.sectionLead}><span>Sage turns every call into forward motion</span><h2>Listen. Check. Answer. Capture.</h2></div><div className={styles.outcomeRow}>{steps.map(([h,p],i)=><article key={h}><b>{String(i+1).padStart(2,"0")}</b><h3>{h}</h3><p>{p}</p><ArrowRight /></article>)}</div></section>;
}

function Scenarios({ active, setActive, concept }: { active:number; setActive:(n:number)=>void; concept:ConceptId }) { const s=scenarios[active]; return <section id="calls" className={styles.scenarios}><div className={styles.sectionLead}><span>Real conversations. Useful outcomes.</span><h2>{concept === "calm-control" ? "Pre-built. Store-specific. Always on brand." : concept === "sale-in-call" ? "Sage drives four outcomes." : "Every common question becomes a reason to visit."}</h2></div>{concept === "after-hours" ? <div className={styles.scenarioGallery}>{scenarios.map((item,i)=><article key={item.tab}><div className={styles.scenarioImage} data-image={i}/><b>{item.tab}</b><h3>“{item.q}”</h3><p>{item.a}</p><footer><Check /> {item.outcome}</footer></article>)}</div> : concept === "sale-in-call" ? <div className={styles.saleConversationGrid}>{scenarios.map((item,i)=><article key={item.tab}><b>0{i+1}</b><h3>{["Answer","Know","Sell","Hand off"][i]}</h3><div><small>Caller</small><p>“{item.q}”</p><small>Sage</small><p>“{item.a}”</p></div><footer><Check /> {item.outcome}</footer></article>)}</div> : <><div className={styles.scenarioTabs}>{scenarios.map((x,i)=><button onClick={()=>setActive(i)} className={i===active?styles.active:""} key={x.tab}>{x.tab}</button>)}</div><div className={styles.conversation}><div><small>Caller</small><p>“{s.q}”</p></div><div><small>Sage</small><p>“{s.a}”</p></div><footer><Check /> {s.outcome}</footer></div></>}</section>; }

function CallReceipt() { return <section className={styles.receiptSection}><div className={styles.receipt}><header><span>Call receipt</span><b>Resolved by Sage</b></header><dl><dt>Location</dt><dd>Downtown</dd><dt>Question</dt><dd>Blue Dream availability</dd><dt>Menu answer</dt><dd>Three options in stock</dd><dt>Promotion</dt><dd>Approved offer shared</dd><dt>Visit intent</dt><dd>After work today</dd><dt>Follow-up</dt><dd>Directions texted</dd></dl><footer><CircleCheck /> Next step captured</footer></div><div><span>Every call leaves a trail.</span><h2>Every call moves forward.</h2><p>Sage captures the details your team needs to continue the conversation—or close the sale—without replaying the call.</p><ul><li><Check /> Full call summary</li><li><Check /> Searchable customer intent</li><li><Check /> Clear staff action</li></ul></div></section>; }

function ConversationLibrary() { return <section className={styles.library}><div><span>Conversation library</span><h2>Curated answers. Local pricing. Always controlled.</h2><p>Each common call begins with approved store knowledge, then adapts to the caller’s location and request.</p></div><div className={styles.libraryTray}>{scenarios.map((s,i)=><article key={s.tab}><b>{s.tab}</b><p>“{s.q}”</p><div className={styles.libraryImage} data-image={i} /></article>)}</div></section>; }

function Integrations({ concept }: { concept: ConceptId }) {
  const systems = [[Store,"POS / menu","Live inventory & pricing"],[ShoppingBag,"Promotions","Active deals & rules"],[UserRoundCheck,"Loyalty","Customer history & preferences"],[PhoneCall,"Sage","Answers, sells & captures intent"],[Headphones,"Reports","Call outcomes & insights"]] as const;
  if (concept === "sale-in-call") return <section id="integrations" className={`${styles.integrations} ${styles.saleSystems}`}><h2>Connected to your stack. Powered by your data.</h2><div className={styles.systemRail}>{systems.map(([Icon,label,detail],i)=>{const I=Icon as typeof Store;return <article key={label}><I/><b>{label}</b><span>{detail}</span>{i<systems.length-1&&<ArrowRight className={styles.railArrow}/>}</article>})}</div><p><LockKeyhole/> Secure, read-only connections. Your store remains in control.</p></section>;
  return <section id="integrations" className={styles.integrations}><div className={styles.sectionLead}><span>Connected to your store</span><h2>{concept === "calm-control" ? "One trusted source. Every system." : "Works where you work."}</h2><p>Sage connects to the tools you already use, so store information stays current and every call leaves a usable record.</p></div><div className={styles.integrationLine}>{systems.map(([Icon,label],i)=>{const I=Icon as typeof Store;return <div key={label}><I/><b>{label}</b>{i<systems.length-1&&<ArrowRight className={styles.railArrow}/>}</div>})}</div></section>;
}

function Personalization({ concept }: { concept: ConceptId }) {
  if (concept === "sale-in-call") return <section className={`${styles.personal} ${styles.knownCustomer}`}><div className={styles.knownLead}><span>Personalized for known customers</span><h2>Same question. Better answer when the caller is recognized.</h2><p>With permission and connected customer context, Sage can use purchase history and loyalty status to make the call more useful—without exposing private information.</p></div><div className={styles.knownConversation}><article><header>New caller</header><p><b>Sage</b> Thanks for calling Downtown. How can I help?</p><p><b>Caller</b> Do you have any sativa pre-rolls?</p><p><b>Sage</b> Yes. Want the current options and prices?</p></article><article><header>Known customer <span>Recognized</span></header><p><b>Sage</b> Welcome back. How can I help today?</p><p><b>Caller</b> Do you have any sativa pre-rolls?</p><p><b>Sage</b> Yes. Based on your approved preferences, I can start with the options most similar to your last visit.</p></article></div><ul className={styles.knownBenefits}><li><UserRoundCheck /> Uses approved purchase context</li><li><ShoppingBag /> Remembers permitted preferences</li><li><CircleCheck /> Explains relevant loyalty benefits</li><li><LockKeyhole /> Honors opt-out and privacy rules</li></ul></section>;
  if (concept === "after-hours") return <section className={`${styles.personal} ${styles.afterPersonal}`}><div><span>Personal by nature</span><h2>Every caller gets a personal experience.</h2><p>Sage recognizes returning callers when permission and policy allow, references the right location, and surfaces the context that makes the next answer useful.</p><ul><li><Check /> Recognizes returning customers</li><li><Check /> References approved history and preferences</li><li><Check /> Surfaces relevant products and offers</li><li><Check /> Builds stronger loyalty over time</li></ul></div><div className={styles.personalImage}/><div className={styles.returningCall}><p><b>Sage</b> Hi Alex—welcome back. Looking for something similar to your last Downtown visit?</p><p><b>Caller</b> Yes. That was great.</p><p><b>Sage</b> I found two available options in the same category. Want the details texted to you?</p><footer><CircleCheck /> Permission checked · context applied</footer></div></section>;
  return <section className={styles.personal}><div className={styles.personalImage}/><div><span>Personal, with privacy</span><h2>Greet returning customers. Respect their privacy.</h2><p>When connected data, customer permission, and store policy allow it, Sage can recognize a preferred location, explain loyalty information, and make the next conversation more useful.</p><div className={styles.privacyFlow}><span><UserRoundCheck /> Recognize</span><ArrowRight/><span><ShoppingBag /> Share context</span><ArrowRight/><span><CircleCheck /> Help next</span><ArrowRight/><span><LockKeyhole /> Protect privacy</span></div><small>Customers can opt out of recognition or messaging at any time.</small></div></section>;
}

function Compliance({ concept }: { concept: ConceptId }) {
  const rules = [[ShieldCheck,"Approved knowledge","Only content your team approves and maintains."],[LockKeyhole,"Age-gated flow","Configured around location policy and jurisdiction."],[MapPin,"Location rules","Local hours, offers, inventory and handoffs."],[Headphones,"Human escalation","Sensitive calls reach your team with context."]];
  if (concept === "sale-in-call") return <section id="control" className={`${styles.compliance} ${styles.languageControl}`}><article className={styles.complianceIntro}><span>Built for compliance. Controlled by you.</span><h2>Decide what Sage can say—and what it cannot.</h2><p>You are in control of what Sage may say, what it must never say, and when a person takes over.</p>{["Age verification required","State-specific rules applied","Promotion guardrails","Price-talk controls","Divert to a person when needed","Record and log all conversations"].map(x=><div className={styles.controlToggle} key={x}><span>{x}</span><i>On</i></div>)}</article><article className={styles.approvedLanguage}><h3>Approved language</h3>{["We can explain approved product information.","Please consume responsibly.","For use only by adults 21+.","Would you like these details texted?"].map(x=><p key={x}><Check/> “{x}”</p>)}</article><article className={styles.prohibitedLanguage}><h3>Prohibited language</h3>{["No medical claims","No health claims","No guarantees","No pressure tactics","No dosing advice"].map(x=><p key={x}><b>×</b> {x}</p>)}</article></section>;
  const calmRules = [...rules,[ShieldCheck,"Uncertainty fallback","If Sage is unsure, it asks for clarification or hands off instead of guessing."],[LockKeyhole,"Complete audit trail","Every answer source, outcome, and handoff is recorded for review."]];
  return <section id="control" className={styles.compliance}><div className={styles.sectionLead}><span>Compliance, built in</span><h2>{concept === "calm-control" ? "Control every answer. Stay audit ready." : "Built on trust. Controlled by your team."}</h2><p>You choose what Sage may say, what it must never say, and when a manager takes over.</p></div><div className={styles.rules}>{(concept === "calm-control" ? calmRules : rules).map(([Icon,h,p])=>{const I=Icon as typeof ShieldCheck;return <article key={h as string}><I/><div><h3>{h as string}</h3><p>{p as string}</p></div></article>})}</div><div className={styles.noClaims}><b>No medical claims</b><span>No diagnosis · no treatment advice · no guessing</span></div></section>;
}

function Locations() { return <section className={styles.locations}><div><span>Built for multi-location operations</span><h2>Consistent experience. Local execution.</h2><p>Every store keeps the right hours, policies, menu context, promotions, and handoff rules.</p></div><div>{[["Downtown","Open · closes 10 PM","Local menu & pricing"],["Northside","Open · closes 9 PM","Local policies"],["Westgate","Open · closes 11 PM","Local promotions"],["Lakeside","Open · closes 9 PM","Local staff & contacts"]].map(([n,h,d])=><article key={n}><b>{n}</b><span>{h}</span><small>{d}</small><ArrowRight /></article>)}</div></section>; }

function Setup({ concept }: { concept: ConceptId }) {
  const standard = [["Discover","Add stores, hours, policies and common calls."],["Build","Connect supported systems and approve answers."],["Test","Call Sage yourself and tune every response."],["Launch","Go live when your team is satisfied."]];
  const sale = [["Configure","Connect your menu, set rules, and add approved promotions."],["Test","Run test conversations and review fine-tune responses."],["Pilot","Go live quietly, monitor performance, and optimize."],["Launch","Scale across locations and turn every call into a next step."]];
  const steps = concept === "sale-in-call" ? sale : standard;
  return <section className={`${styles.setup} ${concept === "sale-in-call" ? styles.saleSetup : ""}`}><div className={styles.sectionLead}><span>Build, test, then launch</span><h2>{concept === "after-hours" ? "Launch in days, not months." : concept === "calm-control" ? "Get Sage live in four simple stages." : "Build Sage. Test Sage. Launch Sage."}</h2></div><div>{steps.map(([h,p],i)=><article key={h}>{concept === "calm-control" && <div className={styles.setupImage} data-step={i}/>}<b>{i+1}</b><h3>{h}</h3><p>{p}</p>{concept === "sale-in-call" && <span className={styles.stepMark}>{[<Store key="store"/>,<Headphones key="test"/>,<ArrowRight key="pilot"/>,<PhoneCall key="launch"/>][i]}</span>}</article>)}</div></section>;
}

function FAQ() { const [open,setOpen]=useState(0); const qs=["Can Sage access our live menu?","How does age gating work?","What happens when Sage does not know?","Can Sage recognize returning customers?","Does Sage replace our budtenders?"]; return <section id="faq" className={styles.faq}><h2>Questions operators ask before launch.</h2><div>{qs.map((q,i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown /></button>{open===i&&<p>{answer(i)}</p>}</article>)}</div></section>; }

function RiskReversal() { return <section className={styles.risk}><div><b>Build before you buy</b><span>Test real calls with your store information.</span></div><div><b>No pressure to publish</b><span>Go live only when the answers are right.</span></div><div><b>Human onboarding</b><span>Configure supported systems and guardrails.</span></div><div><b>Clear monthly pricing</b><span>Plans can be changed as your call volume grows.</span></div></section>; }

function Close({ concept }: { concept: ConceptId }) { return <section className={styles.close}><div><span>{conceptNames[concept]}</span><h2>{concept === "sale-in-call" ? "Every call gets a next step." : concept === "calm-control" ? "Your staff takes care of the store. Sage takes care of the phone." : "You handle the experience. Sage handles the phone."}</h2><p>Build Sage with your store information, approved language, and handoff rules. Then call it yourself before going live.</p><Actions /></div></section>; }

function LocalFooter() { return <footer className={styles.localFooter}><div className={styles.logo}><i />BAMBOO AI</div><div><b>Product</b><a href="#calls">How Sage works</a><a href="#integrations">Integrations</a></div><div><b>Trust</b><a href="#control">Compliance</a><a href="#faq">Questions</a></div><div><b>Company</b><span>Privacy</span><span>Terms</span></div></footer>; }

function answer(i:number){return ["Sage can read supported menu and inventory sources for the correct store. Integration availability depends on your current platform.","Age-gated flows are configured around retailer policy and jurisdiction requirements before product discussion.","Sage acknowledges uncertainty and routes the call to the right person with a conversation summary.","When permission, connected data and policy allow it, Sage can use approved customer context without exposing private information.","No. Sage handles repetitive phone work so budtenders can spend more time with in-store customers."][i]}
function camel(id:ConceptId){return id.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())}
